INSERT INTO product (name) VALUES ('Apple');
INSERT INTO product (name) VALUES ('Banana');
INSERT INTO product (name) VALUES ('Cherry');
INSERT INTO product (name) VALUES ('Date');
INSERT INTO product (name) VALUES ('Elderberry');
INSERT INTO product (name) VALUES ('Fig');
INSERT INTO product (name) VALUES ('Grape');
INSERT INTO product (name) VALUES ('Honeydew');
INSERT INTO product (name) VALUES ('Ivy Gourd');
INSERT INTO product (name) VALUES ('Jackfruit');
INSERT INTO product (name) VALUES ('Kiwi');
INSERT INTO product (name) VALUES ('Lemon');
INSERT INTO product (name) VALUES ('Mango');
INSERT INTO product (name) VALUES ('Nectarine');
INSERT INTO product (name) VALUES ('Orange');
INSERT INTO product (name) VALUES ('Papaya');
INSERT INTO product (name) VALUES ('Quince');
INSERT INTO product (name) VALUES ('Raspberry');
INSERT INTO product (name) VALUES ('Strawberry');
INSERT INTO product (name) VALUES ('Tomato'); -- Yes, it's technically a fruit!
